# Generated by Django 4.2.2 on 2023-07-10 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doj', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('degree', models.IntegerField()),
                ('rank', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('policelog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
