# Generated by Django 4.2.2 on 2023-07-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0002_policereg'),
    ]

    operations = [
        migrations.AddField(
            model_name='policereg',
            name='police_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
