# Generated by Django 4.2.2 on 2023-07-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0003_policereg_police_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policereg',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
    ]
