# Generated by Django 4.2.2 on 2023-07-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0004_alter_policereg_doj'),
    ]

    operations = [
        migrations.AddField(
            model_name='policereg',
            name='p_status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
