# Generated by Django 4.2.2 on 2023-07-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0005_policereg_p_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='policereg',
            name='page',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
