# Generated by Django 4.2.2 on 2023-07-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0006_policereg_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policereg',
            old_name='page',
            new_name='p_age',
        ),
    ]
