# Generated by Django 4.2.2 on 2023-07-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0008_prisoner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policereg',
            name='p_age',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
