# Generated by Django 4.2.2 on 2023-07-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0009_alter_policereg_p_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='crimes',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
