# Generated by Django 4.2.2 on 2023-07-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0010_prisoner_crimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='prisoner_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
