# Generated by Django 4.2.2 on 2023-07-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0011_prisoner_prisoner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='from_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
