# Generated by Django 4.2.2 on 2023-07-12 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0016_alter_duty_police_alter_duty_prison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='police',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prison_app.policereg'),
        ),
        migrations.AlterField(
            model_name='duty',
            name='prison',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prison_app.prisoner'),
        ),
    ]
