# Generated by Django 4.2.2 on 2023-07-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0017_alter_duty_police_alter_duty_prison'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='status',
            field=models.CharField(default='Active', max_length=30),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='visitor_status',
            field=models.CharField(default='Disallowed', max_length=30),
        ),
    ]
