# Generated by Django 4.2.2 on 2023-07-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0018_prisoner_status_prisoner_visitor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('action', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=30)),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prison_app.policereg')),
                ('prison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prison_app.prisoner')),
            ],
        ),
    ]
