# Generated by Django 4.2.2 on 2023-07-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0020_parole'),
    ]

    operations = [
        migrations.AddField(
            model_name='parole',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
