# Generated by Django 4.2.2 on 2023-07-13 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0021_parole_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prisoner',
            name='visitor_status',
        ),
    ]
