# Generated by Django 4.2.2 on 2023-07-13 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0022_remove_prisoner_visitor_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('visitor_name', models.CharField(max_length=30)),
                ('visitor_phone', models.CharField(max_length=30)),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prison_app.policereg')),
                ('prison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prison_app.prisoner')),
            ],
        ),
    ]
