# Generated by Django 4.2.2 on 2023-08-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0023_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_relation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='visitor_time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
