# Generated by Django 4.2.2 on 2023-08-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0025_alter_visitor_visitor_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='dutyenddate',
            field=models.DateField(null=True),
        ),
    ]
