# Generated by Django 4.2.2 on 2023-08-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0026_duty_dutyenddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
