# Generated by Django 4.2.2 on 2023-08-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0027_prisoner_address_prisoner_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='remarks',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
