# Generated by Django 4.2.3 on 2023-08-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0028_remarks_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='dutystartdate',
            field=models.DateField(null=True),
        ),
    ]
