# Generated by Django 4.2.3 on 2023-08-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison_app', '0029_duty_dutystartdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='visitor_alloted_time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
